# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/configuredialog.ui'
#
# Created: Wed Mar 18 16:42:08 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(534, 266)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.configGroupBox = QtGui.QGroupBox(Dialog)
        self.configGroupBox.setTitle("")
        self.configGroupBox.setObjectName("configGroupBox")
        self.formLayout = QtGui.QFormLayout(self.configGroupBox)
        self.formLayout.setObjectName("formLayout")
        self.idLabel = QtGui.QLabel(self.configGroupBox)
        self.idLabel.setObjectName("idLabel")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.idLabel)
        self.idLineEdit = QtGui.QLineEdit(self.configGroupBox)
        self.idLineEdit.setObjectName("idLineEdit")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.idLineEdit)
        self.gfLabel = QtGui.QLabel(self.configGroupBox)
        self.gfLabel.setObjectName("gfLabel")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.gfLabel)
        self.ensLabel = QtGui.QLabel(self.configGroupBox)
        self.ensLabel.setObjectName("ensLabel")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.ensLabel)
        self.meshLabel = QtGui.QLabel(self.configGroupBox)
        self.meshLabel.setObjectName("meshLabel")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.meshLabel)
        self.pathLabel = QtGui.QLabel(self.configGroupBox)
        self.pathLabel.setObjectName("pathLabel")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.pathLabel)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gfLocLineEdit = QtGui.QLineEdit(self.configGroupBox)
        self.gfLocLineEdit.setObjectName("gfLocLineEdit")
        self.horizontalLayout.addWidget(self.gfLocLineEdit)
        self.gfLocButton = QtGui.QPushButton(self.configGroupBox)
        self.gfLocButton.setObjectName("gfLocButton")
        self.horizontalLayout.addWidget(self.gfLocButton)
        self.formLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ensLocLineEdit = QtGui.QLineEdit(self.configGroupBox)
        self.ensLocLineEdit.setObjectName("ensLocLineEdit")
        self.horizontalLayout_2.addWidget(self.ensLocLineEdit)
        self.ensLocButton = QtGui.QPushButton(self.configGroupBox)
        self.ensLocButton.setObjectName("ensLocButton")
        self.horizontalLayout_2.addWidget(self.ensLocButton)
        self.formLayout.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.meshLocLineEdit = QtGui.QLineEdit(self.configGroupBox)
        self.meshLocLineEdit.setObjectName("meshLocLineEdit")
        self.horizontalLayout_3.addWidget(self.meshLocLineEdit)
        self.meshLocButton = QtGui.QPushButton(self.configGroupBox)
        self.meshLocButton.setObjectName("meshLocButton")
        self.horizontalLayout_3.addWidget(self.meshLocButton)
        self.formLayout.setLayout(3, QtGui.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pathLocLineEdit = QtGui.QLineEdit(self.configGroupBox)
        self.pathLocLineEdit.setObjectName("pathLocLineEdit")
        self.horizontalLayout_4.addWidget(self.pathLocLineEdit)
        self.pathLocButton = QtGui.QPushButton(self.configGroupBox)
        self.pathLocButton.setObjectName("pathLocButton")
        self.horizontalLayout_4.addWidget(self.pathLocButton)
        self.formLayout.setLayout(4, QtGui.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.gridLayout.addWidget(self.configGroupBox, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.idLineEdit, self.gfLocLineEdit)
        Dialog.setTabOrder(self.gfLocLineEdit, self.gfLocButton)
        Dialog.setTabOrder(self.gfLocButton, self.ensLocLineEdit)
        Dialog.setTabOrder(self.ensLocLineEdit, self.ensLocButton)
        Dialog.setTabOrder(self.ensLocButton, self.meshLocLineEdit)
        Dialog.setTabOrder(self.meshLocLineEdit, self.meshLocButton)
        Dialog.setTabOrder(self.meshLocButton, self.pathLocLineEdit)
        Dialog.setTabOrder(self.pathLocLineEdit, self.pathLocButton)
        Dialog.setTabOrder(self.pathLocButton, self.buttonBox)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Configure Fieldwork Model Source Step", None, QtGui.QApplication.UnicodeUTF8))
        self.idLabel.setText(QtGui.QApplication.translate("Dialog", "Identifier:  ", None, QtGui.QApplication.UnicodeUTF8))
        self.gfLabel.setText(QtGui.QApplication.translate("Dialog", "GF Filename:  ", None, QtGui.QApplication.UnicodeUTF8))
        self.ensLabel.setText(QtGui.QApplication.translate("Dialog", "Ensemble Filename:  ", None, QtGui.QApplication.UnicodeUTF8))
        self.meshLabel.setText(QtGui.QApplication.translate("Dialog", "Mesh Filename:  ", None, QtGui.QApplication.UnicodeUTF8))
        self.pathLabel.setText(QtGui.QApplication.translate("Dialog", "Path:  ", None, QtGui.QApplication.UnicodeUTF8))
        self.gfLocButton.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.ensLocButton.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.meshLocButton.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.pathLocButton.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))

